// Enum 타입 정의

export enum AccommodationStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  UNPUBLISHED = "UNPUBLISHED",
  DELETED = "DELETED",
}

export enum MemberStatus {
  ACTIVE = "ACTIVE",
  DELETED = "DELETED",
  DORMANT = "DORMANT",
}

export enum PaymentMethod {
  CARD = "CARD",
  VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT",
  EASY_PAY = "EASY_PAY",
  MOBILE_PHONE = "MOBILE_PHONE",
  BANK_TRANSFER = "BANK_TRANSFER",
  CULTURE_GIFT_CARD = "CULTURE_GIFT_CARD",
  BOOK_GIFT_CARD = "BOOK_GIFT_CARD",
  GAME_GIFT_CARD = "GAME_GIFT_CARD",
  UNKNOWN = "UNKNOWN",
}

export enum PaymentStatus {
  READY = "READY",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_FOR_DEPOSIT = "WAITING_FOR_DEPOSIT",
  DONE = "DONE",
  CANCELED = "CANCELED",
  PARTIAL_CANCELED = "PARTIAL_CANCELED",
  ABORTED = "ABORTED",
  EXPIRED = "EXPIRED",
}

export enum ReservationStatus {
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  CANCELLATION_FAILED = "CANCELLATION_FAILED",
  COMPLETED = "COMPLETED",
  EXPIRED = "EXPIRED",
}

export enum ReviewSortType {
  LATEST = "LATEST",
  HIGHEST_RATING = "HIGHEST_RATING",
  LOWEST_RATING = "LOWEST_RATING",
}

export enum ReviewStatus {
  PUBLISHED = "PUBLISHED",
  DELETE = "DELETE",
  HIDDEN = "HIDDEN",
}

export enum WishlistStatus {
  ACTIVE = "ACTIVE",
  DELETED = "DELETED",
}

export enum AccommodationType {
  ENTIRE_PLACE = "ENTIRE_PLACE",
  PRIVATE_ROOM = "PRIVATE_ROOM",
  SHARED_ROOM = "SHARED_ROOM",
  HOTEL_ROOM = "HOTEL_ROOM",
  HOSTEL = "HOSTEL",
  VILLA = "VILLA",
  GUESTHOUSE = "GUESTHOUSE",
  BNB = "BNB",
  RESORT = "RESORT",
  APARTMENT = "APARTMENT",
  HOUSE = "HOUSE",
  TENT = "TENT",
  BOAT = "BOAT",
  TREEHOUSE = "TREEHOUSE",
  CAMPER_VAN = "CAMPER_VAN",
  CASTLE = "CASTLE",
}

export enum AmenityType {
  WIFI = "WIFI",
  TV = "TV",
  AIR_CONDITIONER = "AIR_CONDITIONER",
  AIR_CONDITIONING = "AIR_CONDITIONING",
  HEATING = "HEATING",
  KITCHEN = "KITCHEN",
  WASHER = "WASHER",
  DRYER = "DRYER",
  PARKING = "PARKING",
  POOL = "POOL",
  GYM = "GYM",
  HAIR_DRYER = "HAIR_DRYER",
  IRON = "IRON",
  SHAMPOO = "SHAMPOO",
  BED_LINENS = "BED_LINENS",
  EXTRA_PILLOWS = "EXTRA_PILLOWS",
  CRIB = "CRIB",
  HIGH_CHAIR = "HIGH_CHAIR",
  DISHWASHER = "DISHWASHER",
  COFFEE_MACHINE = "COFFEE_MACHINE",
  MICROWAVE = "MICROWAVE",
  REFRIGERATOR = "REFRIGERATOR",
  ELEVATOR = "ELEVATOR",
  HOT_TUB = "HOT_TUB",
  SMOKE_ALARM = "SMOKE_ALARM",
  CARBON_MONOXIDE_ALARM = "CARBON_MONOXIDE_ALARM",
  FIRE_EXTINGUISHER = "FIRE_EXTINGUISHER",
  PETS_ALLOWED = "PETS_ALLOWED",
  OUTDOOR_SPACE = "OUTDOOR_SPACE",
  BBQ_GRILL = "BBQ_GRILL",
  BALCONY = "BALCONY",
}

// 예약 필터 타입
export enum ReservationFilterType {
  UPCOMING = "UPCOMING",
  PAST = "PAST",
  CANCELLED = "CANCELLED",
}
