// Enum 타입 정의

export enum AccommodationStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  UNPUBLISHED = "UNPUBLISHED",
  DELETED = "DELETED",
}

export enum MemberStatus {
  ACTIVE = "ACTIVE",
  DELETED = "DELETED",
  DORMANT = "DORMANT",
}

export enum PaymentMethod {
  CARD = "CARD",
  VIRTUAL_ACCOUNT = "VIRTUAL_ACCOUNT",
  EASY_PAY = "EASY_PAY",
  MOBILE_PHONE = "MOBILE_PHONE",
  BANK_TRANSFER = "BANK_TRANSFER",
  CULTURE_GIFT_CARD = "CULTURE_GIFT_CARD",
  BOOK_GIFT_CARD = "BOOK_GIFT_CARD",
  GAME_GIFT_CARD = "GAME_GIFT_CARD",
  UNKNOWN = "UNKNOWN",
}

export enum PaymentStatus {
  READY = "READY",
  IN_PROGRESS = "IN_PROGRESS",
  WAITING_FOR_DEPOSIT = "WAITING_FOR_DEPOSIT",
  DONE = "DONE",
  CANCELED = "CANCELED",
  PARTIAL_CANCELED = "PARTIAL_CANCELED",
  ABORTED = "ABORTED",
  EXPIRED = "EXPIRED",
}

export enum ReservationStatus {
  PAYMENT_PENDING = "PAYMENT_PENDING",
  CONFIRMED = "CONFIRMED",
  CANCELLED = "CANCELLED",
  CANCELLATION_FAILED = "CANCELLATION_FAILED",
  EXPIRED = "EXPIRED",
}

export enum ReviewSortType {
  LATEST = "LATEST",
  HIGHEST_RATING = "HIGHEST_RATING",
  LOWEST_RATING = "LOWEST_RATING",
}

export enum ReviewStatus {
  PUBLISHED = "PUBLISHED",
  DELETE = "DELETE",
  HIDDEN = "HIDDEN",
}

export enum WishlistStatus {
  ACTIVE = "ACTIVE",
  DELETED = "DELETED",
}

export enum AccommodationType {
  ENTIRE_PLACE = "ENTIRE_PLACE",
  PRIVATE_ROOM = "PRIVATE_ROOM",
  SHARED_ROOM = "SHARED_ROOM",
  HOSTEL = "HOSTEL",
}

export enum AmenityType {
  WIFI = "WIFI",
  TV = "TV",
  AIR_CONDITIONING = "AIR_CONDITIONING",
  HEATING = "HEATING",
  KITCHEN = "KITCHEN",
  WASHER = "WASHER",
  DRYER = "DRYER",
  PARKING = "PARKING",
  POOL = "POOL",
  GYM = "GYM",
  BED_LINENS = "BED_LINENS",
  EXTRA_PILLOWS = "EXTRA_PILLOWS",
}





